# -*- coding: utf-8 -*-
"""P1HPC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QjqN7pRcOX_EbdLrVX142wH5JMYM-LYi

# COMPUTACIÓN DE ALTAS PRESTACIONES
## Práctica #1 - Procesamiento de datos mediante Apache Spark

* Martha María Del Toro Carballo       100486134@alumnos.uc3m.es
* Brandon Solo                         100405959@alumnos.uc3m.es
* Manuel Santiago Férnandez Arias      manuefer@inf.uc3m.es

### Inicializando Spark
"""

# !apt-get update
# !apt-get install openjdk-8-jdk-headless -qq > /dev/null
# !wget -q https://dlcdn.apache.org/spark/spark-3.1.3/spark-3.1.3-bin-hadoop3.2.tgz
# !tar xf spark-3.1.3-bin-hadoop3.2.tgz
# !pip install -q findspark

import os
import sys
# os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
# os.environ["SPARK_HOME"] = "/content/spark-3.1.3-bin-hadoop3.2"
import pyspark.sql.functions

import findspark
findspark.init()

num_cores = sys.argv[1]


from pyspark.sql import SparkSession
from pyspark import SparkContext, SparkConf

# conf = SparkConf().set('spark.ui.port', '4050')
# sc = SparkContext(conf=conf)
spark = SparkSession.builder.master(f'local[{num_cores}]').getOrCreate()


from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

"""### Otras librerías a usar"""

from datetime import datetime
from time import time
import numpy as np
from csv import writer
import matplotlib.pyplot as plt
from operator import add
from pyspark.sql import functions as F
import os
import pandas as pd
from operator import add
import seaborn as sns

"""### Funciones"""

def calcularRendimiento(results, cant_datos):
    t_0 = time()
    # if isinstance(results, pyspark.rdd.RDD):
    #     results.sortBy(lambda x: x[1], False)
    result_count = results.count() # Acción
    t_1 = time()
    tiempo_ejecucion = np.round(t_1 - t_0, 3)
    velocidad_ejecucion = round(cant_datos / tiempo_ejecucion, 2)

    return result_count , tiempo_ejecucion , velocidad_ejecucion

def interpretar_rendimiento(tiempo_ejecucion,velocidad_ejecucion,cant_datos):
    print(f'Han transcurrido {tiempo_ejecucion} segundos de ejecución.')
    print(f'Cantidad de datos procesados: {cant_datos}')
    print(f'Velocidad de procesamiento: {velocidad_ejecucion} registros/s')
  
def mostrar_grafico(data1, data2, title, cant_datos, legend = ['sql', 'rdd', 'data_frame'], n_cores = 4):
    x = [i for i in range(1,n_cores + 1)] # n_cores

    plt.figure(1, [14, 5], 150)

    plt.subplot(121)
    plt.title(title)
    plt.ylabel("Tiempo de ejecución (seg.)")
    plt.xlabel("Número de cores")
    plt.grid(True)
    plt.xticks(x)

    for y in data1:
        plt.plot(x, y)

    plt.legend(legend)

    plt.subplot(122)
    plt.title("Cantidad de registros: " + str(cant_datos))
    plt.ylabel("Registros procesados por segundo")
    plt.xlabel("Número de cores")
    plt.grid(True)
    plt.xticks(x)

    for y in data2:
        plt.plot(x, y)

    plt.legend(legend)

    plt.show()

def mostrar_resultados_rdd(results,columns,nfilas = 10):
    df = pd.DataFrame(results.take(nfilas), columns = columns)
    return df.style

def mostar_resultados_sql_df(results,nfilas = 10):
    return results.limit(nfilas).toPandas()

"""# Obtención de los datos"""

# df = pd.read_parquet('yellow_tripdata_2019-06.parquet')
# df.to_csv('yellow_tripdata_2019-06.csv')

# Datos generales
# path = "yellow_tripdata_2019-06.csv"
# df_data = spark.read.csv(path, header=True, inferSchema=True)

path = "taxi+_zone_lookup.csv"
#df_zones = spark.read.csv(path, header=True, inferSchema=True)
df_zones = spark.read.option("delimiter", ";").csv(path, header=True, inferSchema=True)
sample_prop = sys.argv[2]

from typing import Union, List


def file_belongs_to_included_years(file: str, included_years: List[int]):
    for included_year in included_years:
        if str(included_year) in file:
            return True
    return False


# Load all the information
start = time()
# taxi_info = spark.read.csv("/content/drive/MyDrive/MASTER'S YEAR/Computación de Altas Prestaciones/P1/data/").cache()

files_to_include = [f"data/{x}" for x in os.listdir("data") if x.endswith(".parquet")]
included_years = [x for x in range(2022, 2023)]
files_to_include = [file for file in files_to_include if file_belongs_to_included_years(file, included_years)]

df_data = spark.read.format("parquet").option("inferSchema", "true").option("timestampFormat",
                                                                              "yyyy-MM-dd HH:mm:ss").option("header",
                                                                                                            "true").option(
    "mode", "DROPMALFORMED").load(files_to_include).sample(float(sample_prop))

taxi_info_count = df_data.count()
end = time()
print(f"Count: {taxi_info_count}\nTime: {end-start}s")

"""# Limpieza de Datos

## Análisis previo de los datos

A continuación se hace un breve análisis de los datos
"""

df_data.select("total_amount").describe().show()

df_data.select("tip_amount").describe().show()

df_data.select("trip_distance").describe().show()

df_data.select("passenger_count").describe().show()

"""Representación de la dispersión y valores atípicos de propinas mediante un boxplot"""

data = df_data.select("tip_amount").rdd.flatMap(lambda x: x).collect()

# plt.boxplot(data)
# plt.show()

"""## Limpieza de datos nulos"""

# -------- Limpieza en datos generales --------
rows1 = df_data.count()

# Eliminación de nulos
df_data_filtered = df_data.dropna()

rows2 = df_data_filtered.count()

print("Cantidad de filas eliminadas: " + str(rows1 - rows2))

# -------- Limpieza en datos de zonas --------
rows1 = df_zones.count()

# Eliminación de nulos
df_zones_filtered = df_zones.dropna()

listaNulos = ["Unknown", "NA", "N/A"]

rdd_df_filtered = df_zones_filtered.rdd.filter(lambda x: x.Borough not in listaNulos)     \
                                       .filter(lambda x: x.Zone not in listaNulos)        \
                                       .filter(lambda x: x.service_zone not in listaNulos)

df_zones_filtered = spark.createDataFrame(rdd_df_filtered)
rows2 = df_zones_filtered.count()

print("Cantidad de filas eliminadas: " + str(rows1 - rows2))

"""## Eliminación de valores sin sentido lógico

A partir del análisis previo de los datos se detectaron valores negativos o iguales a 0. Por tanto, se procede a eliminar las filas que contienen:
- Propinas negativas
- Distancia de viajes negativa o igual a 0
- Coste del viaje negativo o igual a 0
- Tiempos sin sentido (llegada antes o igual que salida)
"""

rows1 = df_data_filtered.count()

# Filtrando propinas, importes negativos y tiempos
rdd_df_filtered = df_data_filtered.rdd.filter(lambda x: x.tip_amount >= 0) \
                                      .filter(lambda x: x.trip_distance > 0) \
                                      .filter(lambda x: x.total_amount >= 0) \
                                      .filter(lambda x: x.passenger_count > 0) \
                                      .filter(lambda x: x.tpep_pickup_datetime < x.tpep_dropoff_datetime)

df_data_filtered = spark.createDataFrame(rdd_df_filtered)
rows2 = df_data_filtered.count()

print("Cantidad de filas eliminadas: " + str(rows1 - rows2))

"""## Filtrado de los valores atípicos"""

quantiles = df_data_filtered.approxQuantile("tip_amount", [0.25, 0.75], 0.0)
Q1 = quantiles[0]
Q3 = quantiles[1]
IQR = Q3 - Q1
upperRange = Q3 + 3*IQR
rdd_df_filtered = df_data_filtered.rdd.filter(lambda x: x.tip_amount < upperRange)

df_data_filtered = spark.createDataFrame(rdd_df_filtered)
rows2 = df_data_filtered.count()

print("Cantidad de filas eliminadas: " + str(rows1 - rows2))

"""Representación de la dispersión resultante del filtrado de valores atípicos teniendo en cuenta las propinas mediante un boxplot"""

data = df_data_filtered.select("tip_amount").rdd.flatMap(lambda x: x).collect()

# plt.boxplot(data)
# plt.show()

"""## Conversión del formato de tiempo"""

from pyspark.sql.functions import to_timestamp

df_data_final = df_data_filtered.withColumn("tpep_pickup_datetime", to_timestamp("tpep_pickup_datetime"))
df_data_final = df_data_final.withColumn("tpep_dropoff_datetime", to_timestamp("tpep_dropoff_datetime"))

"""Ahora que tenemos las columnas de Pickup y Dropoff formateadas a *timestamp*, se filtran los datos buscando un orden lógico de fechas:

*   El tiempo de llegada es mayor que el de salida
*   Los tiempos son diferentes
"""

df_data_final = df_data_final.rdd.filter(lambda x: (x.tpep_dropoff_datetime - x.tpep_pickup_datetime).seconds > 0)
df_data_final = spark.createDataFrame(df_data_final)

"""## Join con los datos de las zonas"""

# ------- JOIN PULocation con la tabla de zonas -------
df_data_j = df_data_final.join(df_zones_filtered, on=[df_data_final.PULocationID == df_zones_filtered.LocationID], how = 'inner')

# Eliminación de columna redundante 
df_data_j = df_data_j.drop("LocationID")

# Renombrado de las nuevas columnas  
df_data_j = df_data_j.withColumnRenamed("Borough","PUBorough")
df_data_j = df_data_j.withColumnRenamed("Zone","PUZone")
df_data_j = df_data_j.withColumnRenamed("service_zone","PUService_zone")

# ------- JOIN DOLocation con la tabla de zonas -------
df_data_j = df_data_j.join(df_zones_filtered, df_data_final.DOLocationID == df_zones_filtered.LocationID, how='inner')

# Eliminación de columna redundante 
df_data_j = df_data_j.drop("LocationID")

# Renombrado de las nuevas columnas  
df_data_j = df_data_j.withColumnRenamed("Borough","DOBorough")
df_data_j = df_data_j.withColumnRenamed("Zone","DOZone")
df_data_j = df_data_j.withColumnRenamed("service_zone","DOService_zone")

cant_datos = df_data_j.count()

"""# Enunciado de la práctica

Realice los estudios que considere necesarios sobre los datos que contiene los registros de la compañía YellowCab de Nueva York en término de viajes en taxi. Es obligatorio proporcionar al menos tres estudios. Ejemplos de estudios:

1. Velocidad media de los taxis en función de la hora.
2. Viajes en taxi más comunes
3. Registros financieros (propinas, personas, etc.)

Será necesario realizar al menos una ejecución basada en una consulta SQL (spark.sql(.....)), al menos una consulta mediante una concatenación de llamadas a métodos del DataFrame como: select, groupBy, y finalmente una haciendo uso de RDDs. Con el objetivo de estudiar el mejor método de trabajo, uno de los estudios realizados tiene que estar implementado de las tres formas.

Tendrá que preparar un informe, indicando los siguientes aspectos:
*   Tiempo de ejecución.
*   Cantidad de datos procesados en término de número de viajes.
*   Velocidad de procesamiento.
"""

# dict 
results = {}
results["1"] = {}
results["2"] = {}
results["3"] = {}

"""## Consulta #1: Velocidad media de los taxis en función de la hora

##### **SQL**
"""

#df_data_j.createOrReplaceTempView('data')
#temp_results = spark.sql("SELECT COUNT(*) AS CANTIDAD_VIAJES, PUZone, DOZone \
#                     FROM data \
#                     GROUP BY PUZone, DOZone \
#                    ORDER BY CANTIDAD_VIAJES DESC")

"""Rendimiento:"""

#result_count, tiempo_ejecucion, velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
#interpretar_rendimiento(tiempo_ejecucion , velocidad_ejecucion, cant_datos)

#mostar_resultados_sql_df(temp_results)

#temp_res = {
#    "sql": {"count": result_count,
#            "tiempo": tiempo_ejecucion,
#            "velocidad": velocidad_ejecucion
#           }
#}
#results ["1"] = temp_res
#results

"""##### **RDD**

Para obtener el resultado deseado se creó una función velocidad_media que se aplicará al conjunto de datos con map (rdd).
"""

def velocidad_media(x):
    distancia = x.trip_distance
    t_destino = x.tpep_dropoff_datetime
    t_origen = x.tpep_pickup_datetime

    tiempo = (t_destino - t_origen).seconds / 3600

    return (distancia / tiempo, distancia, tiempo)

temp_results = df_data_j.rdd.map(velocidad_media)

"""Rendimiento:"""

result_count , tiempo_ejecucion , velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
interpretar_rendimiento(tiempo_ejecucion, velocidad_ejecucion, cant_datos)

mostrar_resultados_rdd(temp_results,['Velocidad media en millas por hora', 'distancia', 'tiempo'], nfilas = 20)

temp_res = {
    "rdd": {"count": result_count,
            "tiempo": tiempo_ejecucion,
            "velocidad": velocidad_ejecucion
           }
}
results["1"].update(temp_res)

"""##### **DataFrame**

"""

from pyspark.sql.functions import avg, col, unix_timestamp

temp_results = df_data_j.select(["trip_distance", "tpep_dropoff_datetime", "tpep_pickup_datetime"]).withColumn("trip_duration", (unix_timestamp("tpep_dropoff_datetime") - unix_timestamp('tpep_pickup_datetime'))/3600).withColumn("vel_media", col("trip_distance") / (col("trip_duration"))).select(["vel_media", "trip_distance", "trip_duration"])

"""Rendimiento:"""

result_count, tiempo_ejecucion, velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
interpretar_rendimiento(tiempo_ejecucion, velocidad_ejecucion, cant_datos)

mostar_resultados_sql_df(temp_results)

temp_res = {
   "df": {"count": result_count,
           "tiempo": tiempo_ejecucion,
           "velocidad": velocidad_ejecucion
          }
}
results["1"].update(temp_res)

"""## Consulta #2: Viajes en taxi más comunes

##### **SQL**

Esta consulta obtiene los viajes en taxi más comunes en función del destino y del origen de la zona de Nueva York. Esta consulta se realizó mediante SQL y se ordenó la salida descendentemente para hacer un top 10 de los viajes más comunes.
"""

df_data_j.createOrReplaceTempView('data')
temp_results = spark.sql("SELECT COUNT(*) AS CANTIDAD_VIAJES, PUZone, DOZone \
                     FROM data \
                     GROUP BY PUZone, DOZone \
                     ORDER BY CANTIDAD_VIAJES DESC")
# ORDER BY CANTIDAD_VIAJES DESC")

"""Rendimiento:"""

result_count, tiempo_ejecucion, velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
interpretar_rendimiento(tiempo_ejecucion , velocidad_ejecucion, cant_datos)

mostar_resultados_sql_df(temp_results)

temp_res = {
    "sql": {"count": result_count,
            "tiempo": tiempo_ejecucion,
            "velocidad": velocidad_ejecucion
           }
}
results["2"].update(temp_res)

"""##### **RDD**

Esta consulta tiene el mismo propósito que la anterior, pero se realizó mediante RDD, empleando map y reduceByKey
"""

temp_results = df_data_j.rdd.map(lambda x: (str(x.PUBorough + " [" + x.PUZone + "]" + " -> " + x.DOBorough + " [" + x.DOZone + "]"), 1)) \
                       .reduceByKey(add) \
.sortBy(lambda x: x[1], False)

"""Rendimiento:"""

result_count, tiempo_ejecucion, velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
interpretar_rendimiento(tiempo_ejecucion , velocidad_ejecucion, cant_datos)

mostrar_resultados_rdd(temp_results,['Trayecto', 'Cantidad de Viajes'])

temp_res = {
    "rdd": {"count": result_count,
            "tiempo": tiempo_ejecucion,
            "velocidad": velocidad_ejecucion
           }
}
results["2"].update(temp_res)

"""##### **DataFrame**

"""

# temp_results = df_data_j.groupBy()

"""Rendimiento:"""

#result_count, tiempo_ejecucion, velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
#interpretar_rendimiento(tiempo_ejecucion, velocidad_ejecucion6, cant_datos)

#mostar_resultados_sql_df(temp_results)

#temp_res = {
#    "df": {"count": result_count,
#            "tiempo": tiempo_ejecucion,
#            "velocidad": velocidad_ejecucion
#           }
#}
#results ["2"] = temp_res
#results

"""## Consulta #3: Propina media en funcion del número de pasajeros

##### **SQL**

Para obtener el resultado deseado mediante SQL agrupamos el resultado por el número de pasajeros y para cada uno se realiza la media.
"""

df_data_j.createOrReplaceTempView('data')
temp_results = spark.sql("SELECT passenger_count, AVG(tip_amount) \
                     FROM data \
                     GROUP BY passenger_count \
                     ORDER BY passenger_count ASC")

"""Rendimiento:"""

result_count , tiempo_ejecucion , velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
interpretar_rendimiento(tiempo_ejecucion , velocidad_ejecucion, cant_datos)

mostar_resultados_sql_df(temp_results)

temp_res = {
    "sql": {"count": result_count,
            "tiempo": tiempo_ejecucion,
            "velocidad": velocidad_ejecucion
           }
}
results["3"].update(temp_res)

"""##### **RDD**

Para obtener el resultado deseado mediante RDD Se usarán las funciones de transformación map y reduceByKey mediante cual se asignará a cada clave (Passenger_count) el valor de la propina media que le corresponde a cada una.
"""

temp_results = df_data_j.rdd.map(lambda x: (x.passenger_count, (x.tip_amount, 1))) \
                       .reduceByKey(lambda x, y: (x[0]+y[0], x[1]+y[1])) \
                       .map(lambda x: (x[0], x[1][0] / x[1][1]))

"""Rendimiento:"""

result_count, tiempo_ejecucion, velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
interpretar_rendimiento(tiempo_ejecucion, velocidad_ejecucion, cant_datos)

mostrar_resultados_rdd(temp_results,['Número de pasajeros', 'Propina media'])

temp_res = {
    "rdd": {"count": result_count,
            "tiempo": tiempo_ejecucion,
            "velocidad": velocidad_ejecucion
           }
}
results["3"].update(temp_res)

"""##### **DataFrame**

El resultado se obtiene aplicando una agrupación por el campo "passenger_count", donde con el resultado obtenido se realiza una agregación por "tip_amount" (propina) y se ordena ascendentemente por el número de pasajeros.
"""

temp_results = df_data_j.groupBy("passenger_count") \
                    .agg(F.mean('tip_amount')) \
                   .orderBy('passenger_count')
# .agg(F.mean('tip_amount'), F.min('tip_amount'), F.max('tip_amount')) \

"""Rendimiento:"""

result_count, tiempo_ejecucion, velocidad_ejecucion =  calcularRendimiento(temp_results, cant_datos)
interpretar_rendimiento(tiempo_ejecucion, velocidad_ejecucion, cant_datos)

mostar_resultados_sql_df(temp_results)

temp_res = {
    "df": {"count": result_count,
            "tiempo": tiempo_ejecucion,
            "velocidad": velocidad_ejecucion
           }
}
results["3"].update(temp_res)
"""## Guardando los resultados"""

"""## Comparando las gráficas de los resultados"""

normalized = pd.json_normalize(results).to_dict(orient='records')
records = []
for num_consulta, v in results.items():
    for method, v2 in v.items():
        records.append([f"{num_consulta}_{method}", num_consulta, method, v2["count"], v2["tiempo"], v2["velocidad"]])
results_df = pd.DataFrame(records, columns=["id", "num_consulta", "method", "count", "tiempo", "velocidad"])
results_df.set_index("id", inplace=True)

results_df.to_csv(f'final_results/final_result_{num_cores}_{sample_prop}.csv', sep=';')
